# Header
menu:
  Home: /en/home
  Blog: /en
  Communication: /en/communication
  About_me: /en/about_me
rss: /atom.xml

# Miscellaneous
google_analytics: true

# internationalization
internationalization: true

language: en