# Header
menu:
  Home: /
  Blog: /archives
  Communication: /communication
  About_me: /about_me

# Miscellaneous
google_analytics: true

# language
i18n_dir: :lang
language: en

language:
- zh-cn
- en

