# Header
menu:
  Home: /home
  Blog: /
  Communication: /communication
  About_me: /about_me
rss: /atom.xml

# Miscellaneous
google_analytics: true

# internationalization
internationalization: true

sourceRoot: /en